use color_eyre::Result;

use crate::system::shell;

/// Scan the current machine and generate a profile YAML to stdout
pub async fn run_export() -> Result<()> {
    println!("# Generated by: devconf export");
    println!("# Date: {}", chrono_now());
    println!();

    // Scan winget packages
    let winget_packages = scan_winget().await?;

    // Scan scoop packages
    let scoop_packages = scan_scoop().await?;

    // Scan environment variables of interest
    let env_vars = scan_env_vars();

    // Generate YAML
    let hostname = std::env::var("COMPUTERNAME").unwrap_or_else(|_| "unknown".to_string());
    println!("profile: {}", hostname.to_lowercase());
    println!();
    println!("packages:");

    if !winget_packages.is_empty() {
        println!("  # --- winget ({} packages) ---", winget_packages.len());
        for pkg in &winget_packages {
            println!("  - winget: {}", pkg);
        }
    }

    if !scoop_packages.is_empty() {
        println!("  # --- scoop ({} packages) ---", scoop_packages.len());
        for pkg in &scoop_packages {
            println!("  - scoop: {}", pkg);
        }
    }

    println!();
    println!("configs: []");
    println!();

    if !env_vars.is_empty() {
        println!("env:");
        for (key, value) in &env_vars {
            // Escape values that might contain special YAML characters
            if value.contains(':') || value.contains('#') || value.contains('"') {
                println!("  {}: \"{}\"", key, value.replace('"', "\\\""));
            } else {
                println!("  {}: {}", key, value);
            }
        }
    } else {
        println!("env: {{}}");
    }

    println!();
    println!("path: []");
    println!();
    println!("actions: []");

    Ok(())
}

/// Get current date/time as a string (no chrono dependency, use simple approach)
fn chrono_now() -> String {
    // Use PowerShell would be overkill; just use the system time
    let now = std::time::SystemTime::now();
    let duration = now
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let secs = duration.as_secs();
    // Simple ISO-ish date: days since epoch
    let days = secs / 86400;
    let years_approx = 1970 + (days / 365);
    format!("{} (unix: {})", years_approx, secs)
}

/// Scan installed winget packages
async fn scan_winget() -> Result<Vec<String>> {
    let cmd = "winget list --accept-source-agreements --disable-interactivity 2>$null | Select-Object -Skip 2";
    let output = shell::run_powershell(cmd).await?;

    if !output.success {
        tracing::warn!("winget list failed, skipping winget scan");
        return Ok(Vec::new());
    }

    let mut packages = Vec::new();
    let mut found_separator = false;

    for line in output.stdout.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        // winget output has a separator line with dashes
        if trimmed.starts_with("---") || trimmed.starts_with("───") {
            found_separator = true;
            continue;
        }

        if !found_separator {
            continue;
        }

        // Parse line: Name  Id  Version  [Available]  [Source]
        // The Id column is the most reliable identifier
        let parts: Vec<&str> = trimmed.split_whitespace().collect();
        if parts.len() >= 2 {
            // Try to find a package ID (contains a dot, like "Microsoft.PowerShell")
            for part in &parts {
                if part.contains('.') && part.len() > 3 {
                    // Filter out version numbers (contain only dots and digits)
                    let is_version = part.chars().all(|c| c.is_ascii_digit() || c == '.');
                    if !is_version {
                        packages.push(part.to_string());
                        break;
                    }
                }
            }
        }
    }

    packages.sort();
    packages.dedup();
    Ok(packages)
}

/// Scan installed scoop packages
async fn scan_scoop() -> Result<Vec<String>> {
    let cmd = "scoop list 2>$null";
    let output = shell::run_powershell(cmd).await?;

    if !output.success {
        tracing::info!("scoop not available or no packages installed");
        return Ok(Vec::new());
    }

    let mut packages = Vec::new();
    let mut found_separator = false;

    for line in output.stdout.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("Installed") {
            continue;
        }
        if trimmed.starts_with("---") || trimmed.starts_with("───") || trimmed.starts_with("Name") {
            found_separator = true;
            continue;
        }
        if !found_separator {
            continue;
        }
        // First column is the package name
        if let Some(name) = trimmed.split_whitespace().next() {
            packages.push(name.to_string());
        }
    }

    packages.sort();
    packages.dedup();
    Ok(packages)
}

/// Scan notable user environment variables
fn scan_env_vars() -> Vec<(String, String)> {
    let interesting_prefixes = [
        "JAVA_HOME",
        "MAVEN_",
        "GRADLE_",
        "GOPATH",
        "GOROOT",
        "CARGO_HOME",
        "RUSTUP_HOME",
        "NODE_",
        "NPM_",
        "PYTHON",
        "VIRTUAL_ENV",
        "CONDA",
        "DOCKER_",
        "KUBECONFIG",
        "AWS_",
        "AZURE_",
        "GCP_",
        "ZED_",
        "EDITOR",
        "VISUAL",
        "STARSHIP_",
    ];

    let mut vars = Vec::new();
    for (key, value) in std::env::vars() {
        for prefix in &interesting_prefixes {
            if key.starts_with(prefix) {
                vars.push((key.clone(), value.clone()));
                break;
            }
        }
    }
    vars.sort_by(|a, b| a.0.cmp(&b.0));
    vars
}
